apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ningendo7/terraform-multi-region-platform.git
    targetRevision: main
    path: kubernetes/karpenter-nodepool
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
