apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "3.5.0"
    helm:
      values: |
        clusterName: terraform-multi-region-platform-prod

        # Explicit, not auto-detected — same reasoning as us-east-1's.
        #
        # NOTE: vpcId is AWS-assigned — it changes every time the vpc
        # stack is destroyed and recreated. Update this value after any
        # fresh `vpc` apply.
        region: us-west-2
        vpcId: vpc-0567f24c9fd573f51

        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::807906459006:role/terraform-multi-region-platform-prod-usw2-lb-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
