apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ningendo7/terraform-multi-region-platform.git
    targetRevision: main
    path: kubernetes/demo-app-us-west-2
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
